services:
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: ruser
      MYSQL_PASSWORD: localpw
      MYSQL_DATABASE: testdb
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: "#[Master 서버 IP]"  # Master 서버 IP
    ports:
      - "3306:3306"
    command: --server-id=2
    volumes:
      - ./data:/var/lib/mysql
      - ./back-up:/back-up  # 파일 복사가 필요하여 생성
networks:
  mysql-network:
    driver: bridge