services:
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.10.2'
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://host.docker.internal:9200
    ports:
      - "5601:5601"